package es.taw.grupo1.dto;

import lombok.Data;

@Data
public class SesionDTO {
    private Integer id;
    private String dia;
    private Integer rutinaIdrutina;

    // Constructors, getters, setters, etc. can be generated by Lombok or manually created if needed
}